title: Political History Network
description: Description here.

url: http://kkashin.github.io/polhistorynetwork/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Conference
   url: /conference
 - title: Participants
   url: /participants
 - title: Past Events
   url: /pastevents
 - title: Organizers
   url: /organizers
 - title: Contact
   url: /contact

social:
   email: ziblatt@gov.harvard.edu

#google_analytics: "UA"
