title: Political History Network
description: Description Here.

url: http://kkashin.github.com/long-haul
baseurl: "/long-haul"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: kkashin
   twitter: kostyakashin
   facebook: kkashin
   email: brimaidesigns@gmail.com

#google_analytics: "UA-"
